"use client"

import './globals.css'
import {Inter} from 'next/font/google'
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import {Provider} from "react-redux";
import {persistor, store} from "@/redux/store";
import {PersistGate} from "redux-persist/integration/react";
import {ErrorBoundary} from "next/dist/client/components/error-boundary";
import Error from "@/app/error";
import {Suspense} from "react";
import Loading from "@/loading";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Online Shop Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Provider store={store}>
            <PersistGate persistor={persistor} >
                <Navbar/>
                <Suspense fallback={<Loading />}>
                    <ErrorBoundary errorComponent={<Error/>}>
                        <main className={"flex flex-col min-h-screen"}>{children}</main>
                    </ErrorBoundary>
                </Suspense>
                <Footer/>
            </PersistGate>
        </Provider>
        </body>
        </html>
    )
}
