import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import {CartProvider} from "@/app/providers/CartProvider";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Online Shop Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <CartProvider>
          <Navbar/>
          <main>{children}</main>
          <Footer/>
      </CartProvider>
      </body>
    </html>
  )
}
