import React from 'react';
import {Metadata} from "next";

// export async function generateMetadata({id}) {
//     return {
//         title: id | "Online Shop Next App",
//         description: 'Generated by create next app'
//     }
// }

// async function getProduct({id}){
//     try {
//         const response = await fetch(`https://app.ecwid.com/api/v3/58958138/product/${id}`, {
//             headers: {
//                 "Content-type": "application/json",
//                 "Authorization": "Bearer public_7BxbJGWyDaZfSQqjVS5Ftr4jzXkS43UD"
//             }
//         });
//
//         if (response.ok) {
//             return response.json();
//         } else {
//             throw new Error("Request failed with status " + response.status);
//         }
//     } catch (error) {
//         console.log(error)
//     }
// }
function Product({id}) {
    return <>product</>
    // const product = await getProduct(items.id);
    // return <>
    //     <h1>{product.name}</h1>
    // </>
}

export default Product;