import React from 'react';
import {Metadata} from "next";

export async function generateMetadata({id}) {
    return {
        title: id | "Online Shop Next App",
        description: 'Generated by create next app'
    }
}

const token = "public_dP4DKSy7thCJQhrQbXnFafzJxfmzHVDV";

async function getProduct(id){
    try {
        const response = await fetch(`https://app.ecwid.com/api/v3/storeId/products/${id}`, {
            headers: {
                "Content-type": "application/json",
                "Authorization": "Bearer public_7BxbJGWyDaZfSQqjVS5Ftr4jzXkS43UD"
            }
        });

        if (response.ok) {
            return response.json();
        } else {
            throw new Error("Request failed with status " + response.status);
        }
    } catch (error) {
        console.log(error)
    }
}
async function Product({id}) {
    const product = await getProduct(id);

    return <>
        <h1>{product.name}</h1>
    </>
}

export default Product;